name: Build BullOS for Raspberry Pi 5

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap qemu-user-static binfmt-support \
          git build-essential bc bison flex libssl-dev kmod cpio \
          libncurses5-dev xz-utils parted dosfstools gcc-aarch64-linux-gnu \
          u-boot-tools device-tree-compiler
        
    - name: Build BullOS
      run: |
        chmod +x build_bullos.sh
        sudo ./build_bullos.sh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bullos-rpi5-image
        path: output/bullos-rpi5-*.img.xz
        
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: output/bullos-rpi5-*.img.xz